In [108]:
import numpy as np
import pandas as pd

# for Scaling , Encoding and Polinomial features for Hidden paterns:
from sklearn.preprocessing import MinMaxScaler , OneHotEncoder , PolynomialFeatures 
from sklearn.feature_selection import SelectKBest , f_classif # for classification

# for Imputing na :
from sklearn.impute import SimpleImputer

# Under sampleling for imbalanced data set:
from imblearn.under_sampling import RandomUnderSampler

#For Dimentionality Reduction and as model:
from sklearn.decomposition import PCA

# test case split and Cross validation for right hyper parmeter
from sklearn.model_selection import train_test_split , GridSearchCV

#----------------------------------------------------------------------------------

#MODELS:

# 1) For classificstion type and out target is Binary , Hence we Try with Logistic Regression First:
from sklearn.linear_model import LogisticRegression

# 2) Random Forest for Classification Tasks , Bagging methord may perform well:
from sklearn.ensemble import RandomForestClassifier

# 3) by using simple KNN approch:
from sklearn.neighbors import KNeighborsClassifier

# 4) probability based approch:
from sklearn.naive_bayes import CategoricalNB

# 5) Boosing for bagging with continous improvement:
from sklearn.ensemble import AdaBoostClassifier
from xgboost import XGBClassifier
from sklearn.tree import DecisionTreeClassifier

# 6) at last we also trying Voting and Stacking for improvement in Model:
from sklearn.ensemble import VotingClassifier , StackingClassifier

#----------------------------------------------------------------------------------

# Metrics to calculate Classification type traget:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix , f1_score

#----------------------------------------------------------------------------------

# for Pipeline Creationa and transformimg.
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

#----------------------------------------------------------------------------------

# For chart and visuals.
import matplotlib.pyplot as plt
import seaborn as sns

import joblib

import warnings
warnings.filterwarnings("ignore")

In [2]:
train_data = pd.read_csv("train.csv")

In [3]:
test_data = pd.read_csv("test.csv")

In [4]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 381109 entries, 0 to 381108
Data columns (total 12 columns):
 #   Column                Non-Null Count   Dtype  
---  ------                --------------   -----  
 0   id                    381109 non-null  int64  
 1   Gender                381109 non-null  object 
 2   Age                   381109 non-null  int64  
 3   Driving_License       381109 non-null  int64  
 4   Region_Code           381109 non-null  float64
 5   Previously_Insured    381109 non-null  int64  
 6   Vehicle_Age           381109 non-null  object 
 7   Vehicle_Damage        381109 non-null  object 
 8   Annual_Premium        381109 non-null  float64
 9   Policy_Sales_Channel  381109 non-null  float64
 10  Vintage               381109 non-null  int64  
 11  Response              381109 non-null  int64  
dtypes: float64(3), int64(6), object(3)
memory usage: 34.9+ MB


In [5]:
train_data.shape

(381109, 12)

In [6]:
train_data['Response'].value_counts()

Response
0    334399
1     46710
Name: count, dtype: int64

In [7]:
train_data = train_data[train_data['Annual_Premium'] <150000]

In [8]:
train_data['Response'].value_counts()

Response
0    334241
1     46677
Name: count, dtype: int64

In [96]:
x = prepr_train.drop(columns=['Response'])
y = prepr_train['Response']

In [97]:
under_sampeling = RandomUnderSampler()
x_us , y_us = under_sampeling.fit_resample(x , y)

In [98]:
x_train , x_test , y_train , y_test = train_test_split(x_us , y_us , test_size= 0.3 , random_state= 42)

In [99]:
def results(x_train , x_test , y_train , y_test , model):
    model.fit(x_train,y_train)
    train_predict = model.predict(x_train)
    test_predict = model.predict(x_test)
    print('Train F1_score:',f1_score(y_train , train_predict))
    print('Test F1_score:',f1_score(y_test , test_predict))
    print('Train Accuracy_score:\n',accuracy_score(y_train , train_predict))
    print('Test Accuracy_score:\n',accuracy_score(y_test , test_predict))
    print('Train confusion_matrix:\n',confusion_matrix(y_train , train_predict))
    print('Test confusion_matrix:\n',confusion_matrix(y_test , test_predict))
    print('Train Classification_Report:\n',classification_report(y_train , train_predict))
    print('Test Classification_Report:\n',classification_report(y_test , test_predict))

In [100]:
train_data.select_dtypes(include= 'number').columns

Index(['id', 'Age', 'Driving_License', 'Region_Code', 'Previously_Insured',
       'Annual_Premium', 'Policy_Sales_Channel', 'Vintage', 'Response'],
      dtype='object')

In [101]:
train_data.head()

id  Gender  Age  Driving_License  Region_Code  Previously_Insured  \
0   1    Male   44                1         28.0                   0   
1   2    Male   76                1          3.0                   0   
2   3    Male   47                1         28.0                   0   
3   4    Male   21                1         11.0                   1   
4   5  Female   29                1         41.0                   1   

  Vehicle_Age Vehicle_Damage  Annual_Premium  Policy_Sales_Channel  Vintage  \
0   > 2 Years            Yes         40454.0                  26.0      217   
1    1-2 Year             No         33536.0                  26.0      183   
2   > 2 Years            Yes         38294.0                  26.0       27   
3    < 1 Year             No         28619.0                 152.0      203   
4    < 1 Year             No         27496.0                 152.0       39   

   Response  
0         1  
1         0  
2         1  
3         0  
4         0

In [102]:
num_var = [ 'Age', 'Region_Code',
       'Annual_Premium', 'Policy_Sales_Channel', 'Vintage']

In [103]:
numerical_attribute = Pipeline( steps= [
    ('Scaling',MinMaxScaler())
])

In [104]:
PreProcessing = ColumnTransformer( transformers= [
    ('numerical_data',numerical_attribute,num_var)   
])

In [105]:
model_2_1 = Pipeline( steps=[
    ('Preprocessing',PreProcessing),
    ('RF',RandomForestClassifier(max_depth=10, min_samples_leaf=4, min_samples_split=5))
])

In [106]:
model = RandomForestClassifier(max_depth=15, min_samples_leaf=4, min_samples_split=5)

In [107]:
results(x_train , x_test , y_train , y_test , model)

Train F1_score: 0.8457741076325993
Test F1_score: 0.8396131460329964
Train Accuracy_score:
 0.8251452652814375
Test Accuracy_score:
 0.8172479992021741
Train confusion_matrix:
 [[161763  72521]
 [  9300 224353]]
Test confusion_matrix:
 [[67965 31992]
 [ 4658 95930]]
Train Classification_Report:
               precision    recall  f1-score   support

         0.0       0.95      0.69      0.80    234284
         1.0       0.76      0.96      0.85    233653

    accuracy                           0.83    467937
   macro avg       0.85      0.83      0.82    467937
weighted avg       0.85      0.83      0.82    467937

Test Classification_Report:
               precision    recall  f1-score   support

         0.0       0.94      0.68      0.79     99957
         1.0       0.75      0.95      0.84    100588

    accuracy                           0.82    200545
   macro avg       0.84      0.82      0.81    200545
weighted avg       0.84      0.82      0.81    200545



In [65]:
test_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 127037 entries, 0 to 127036
Data columns (total 11 columns):
 #   Column                Non-Null Count   Dtype  
---  ------                --------------   -----  
 0   id                    127037 non-null  int64  
 1   Gender                127037 non-null  object 
 2   Age                   127037 non-null  int64  
 3   Driving_License       127037 non-null  int64  
 4   Region_Code           127037 non-null  float64
 5   Previously_Insured    127037 non-null  int64  
 6   Vehicle_Age           127037 non-null  object 
 7   Vehicle_Damage        127037 non-null  object 
 8   Annual_Premium        127037 non-null  float64
 9   Policy_Sales_Channel  127037 non-null  float64
 10  Vintage               127037 non-null  int64  
dtypes: float64(3), int64(5), object(3)
memory usage: 10.7+ MB


In [67]:
prepr_test.head()

Gender  Age  Driving_License  Previously_Insured  Vehicle_Age  \
0       1   25                1                   1            0   
1       1   40                1                   0            1   
2       1   47                1                   0            1   
3       1   24                1                   1            0   
4       1   27                1                   1            0   

   Vehicle_Damage  Annual_Premium  Policy_Sales_Channel  Vintage  \
0               0         35786.0                 152.0       53   
1               1         33762.0                   7.0      111   
2               1         40050.0                 124.0      199   
3               1         37356.0                 152.0      187   
4               0         59097.0                 152.0      297   

   Region_group_11-20  Region_group_21-30  Region_group_31-40  \
0                True               False               False   
1               False                True               False   
2               False                True               False   
3               False                True               False   
4               False                True               False   

   Region_group_41-52  
0               False  
1               False  
2               False  
3               False  
4               False

In [68]:
prepr_train.head()

Gender  Age  Driving_License  Previously_Insured  Vehicle_Age  \
0       1   44                1                   0            3   
1       1   76                1                   0            1   
2       1   47                1                   0            3   
3       1   21                1                   1            0   
4       0   29                1                   1            0   

   Vehicle_Damage  Annual_Premium  Policy_Sales_Channel  Vintage  Response  \
0               1         40454.0                  26.0      217       1.0   
1               0         33536.0                  26.0      183       0.0   
2               1         38294.0                  26.0       27       1.0   
3               0         28619.0                 152.0      203       0.0   
4               0         27496.0                 152.0       39       0.0   

   Region_group_11-20  Region_group_21-30  Region_group_31-40  \
0               False                True               False   
1               False               False               False   
2               False                True               False   
3                True               False               False   
4               False               False               False   

   Region_group_41-52  
0               False  
1               False  
2               False  
3               False  
4                True

In [71]:
y_pre = model.predict(prepr_test)

In [73]:
sub = pd.read_csv('sample_submission_iA3afxn.csv')

In [74]:
sub['Response']=y_pre

In [75]:
sub['Response']=sub['Response'].astype(int)

In [76]:
x_test.head()

Gender  Age  Driving_License  Previously_Insured  Vehicle_Age  \
219794       1   52                1                   1            1   
66271        0   50                1                   0            1   
556526       1   44                1                   0            1   
445568       0   22                1                   0            0   
507568       1   24                1                   0            0   

        Vehicle_Damage  Annual_Premium  Policy_Sales_Channel  Vintage  \
219794               0         28291.0                  26.0      142   
66271                1         33168.0                 155.0       58   
556526               1         23553.0                   7.0      217   
445568               1         43346.0                 152.0      185   
507568               1         18479.0                 152.0      124   

        Region_group_11-20  Region_group_21-30  Region_group_31-40  \
219794               False               False               False   
66271                False               False                True   
556526               False               False               False   
445568               False                True               False   
507568                True               False               False   

        Region_group_41-52  
219794               False  
66271                False  
556526               False  
445568               False  
507568               False

In [77]:
sub.to_csv('Sub_RF_unscaled_encoded.csv',index=False)

In [116]:
model_1 = AdaBoostClassifier(random_state= 42)

In [117]:
results(x_train , x_test , y_train , y_test , model_1)

Train F1_score: 0.8206580316134581
Test F1_score: 0.8208255610259009
Train Accuracy_score:
 0.7958913272513181
Test Accuracy_score:
 0.7954823107033334
Train confusion_matrix:
 [[153903  80381]
 [ 15129 218524]]
Test confusion_matrix:
 [[65582 34375]
 [ 6640 93948]]
Train Classification_Report:
               precision    recall  f1-score   support

         0.0       0.91      0.66      0.76    234284
         1.0       0.73      0.94      0.82    233653

    accuracy                           0.80    467937
   macro avg       0.82      0.80      0.79    467937
weighted avg       0.82      0.80      0.79    467937

Test Classification_Report:
               precision    recall  f1-score   support

         0.0       0.91      0.66      0.76     99957
         1.0       0.73      0.93      0.82    100588

    accuracy                           0.80    200545
   macro avg       0.82      0.80      0.79    200545
weighted avg       0.82      0.80      0.79    200545



In [118]:
param_grid = {
    'estimator__max_depth': [1, 2],  
    'estimator__min_samples_split': [5, 10],  
    'estimator__min_samples_leaf': [5, 10]  
}

grid_search = GridSearchCV(AdaBoostClassifier(estimator=DecisionTreeClassifier(), random_state=42), 
                           param_grid, cv=5, scoring='f1', n_jobs=-1, verbose=2)
grid_search.fit(x_train, y_train)

Fitting 5 folds for each of 8 candidates, totalling 40 fits


GridSearchCV(cv=5,
             estimator=AdaBoostClassifier(estimator=DecisionTreeClassifier(),
                                          random_state=42),
             n_jobs=-1,
             param_grid={'estimator__max_depth': [1, 2],
                         'estimator__min_samples_leaf': [5, 10],
                         'estimator__min_samples_split': [5, 10]},
             scoring='f1', verbose=2)

In [121]:
y_pre = model_1.predict(prepr_test)

In [122]:
sub['Response']=y_pre
sub['Response']=sub['Response'].astype(int)
sub.to_csv('Sub_ADABoosting_unscaled_encoded.csv',index=False)

In [125]:
model_3 = AdaBoostClassifier()

In [126]:
results(x_train , x_test , y_train , y_test , model_3)

Train F1_score: 0.8206580316134581
Test F1_score: 0.8208255610259009
Train Accuracy_score:
 0.7958913272513181
Test Accuracy_score:
 0.7954823107033334
Train confusion_matrix:
 [[153903  80381]
 [ 15129 218524]]
Test confusion_matrix:
 [[65582 34375]
 [ 6640 93948]]
Train Classification_Report:
               precision    recall  f1-score   support

         0.0       0.91      0.66      0.76    234284
         1.0       0.73      0.94      0.82    233653

    accuracy                           0.80    467937
   macro avg       0.82      0.80      0.79    467937
weighted avg       0.82      0.80      0.79    467937

Test Classification_Report:
               precision    recall  f1-score   support

         0.0       0.91      0.66      0.76     99957
         1.0       0.73      0.93      0.82    100588

    accuracy                           0.80    200545
   macro avg       0.82      0.80      0.79    200545
weighted avg       0.82      0.80      0.79    200545



In [127]:
model_4 = XGBClassifier()

In [128]:
results(x_train , x_test , y_train , y_test , model_4)

Train F1_score: 0.8365808302197081
Test F1_score: 0.8325805866558141
Train Accuracy_score:
 0.8165201725873354
Test Accuracy_score:
 0.8112792640055848
Train confusion_matrix:
 [[162319  71965]
 [ 13892 219761]]
Test confusion_matrix:
 [[68591 31366]
 [ 6481 94107]]
Train Classification_Report:
               precision    recall  f1-score   support

         0.0       0.92      0.69      0.79    234284
         1.0       0.75      0.94      0.84    233653

    accuracy                           0.82    467937
   macro avg       0.84      0.82      0.81    467937
weighted avg       0.84      0.82      0.81    467937

Test Classification_Report:
               precision    recall  f1-score   support

         0.0       0.91      0.69      0.78     99957
         1.0       0.75      0.94      0.83    100588

    accuracy                           0.81    200545
   macro avg       0.83      0.81      0.81    200545
weighted avg       0.83      0.81      0.81    200545



In [129]:
y_pre = model_4.predict(prepr_test)

In [130]:
sub['Response']=y_pre
sub['Response']=sub['Response'].astype(int)
sub.to_csv('Sub_XGBoosting_unscaled_encoded.csv',index=False)